import type { Metadata } from 'next'
import { Inter,Poppins,Roboto_Mono,Sanchez } from 'next/font/google'
import './globals.css'

const sanchez = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sanchez',
})
const poppins = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sanchez} ${poppins} ${roboto_mono}`}>{children}</body>
    </html>
  )
}
