import type { Metadata } from 'next'
import { Inter,Poppins,Roboto_Mono,Sanchez } from 'next/font/google'
import './globals.css'

const sanchez = Sanchez({weight:['400'],subsets:['latin']})
const poppins = Poppins({weight:['600','800'],subsets:['latin']})
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sanchez.className} ${poppins.className} ${roboto_mono.className}`}>{children}</body>
    </html>
  )
}
